name: Qwickly
values:
  - key: base_url
    value: 'https://au.qwickly.tools'
    enabled: true
    type: default
  - key: client_id
    value: e4aaToBaYUhSyvM1lYwiuboY0QQwmRmBtYwGvJ0a
    enabled: true
    type: secret
  - key: client_secret
    value: GVeLeYuuWTohHplPtoXgaw36nsim93XgQ78Mi2GXH5CP7YnFwwRpeSonD2yJplLmVbtbva0Q6XJuJMHu7jIrejnSBdpnBTP5CxzdrRUT7rCilhV1ykI39MOYjLllFTpE
    enabled: true
    type: secret
  - key: access_token
    value: ''
    enabled: true
    type: secret
  - key: course_identifier
    value: ''
    enabled: true
    type: default
  - key: session_id
    value: ''
    enabled: true
    type: default
  - key: user_identifier
    value: ''
    enabled: true
    type: default
